# -- Main Menu --
# Главное меню сайта (верхняя панель)

[[main]]
  name = "Посты"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Обо мне"
  pageRef = "about"
  weight = 20
  
[[main]]
  name = "Главная"
  pageRef = "/"
  weight = 1
